Update icinga2_prepared_vars.py
bodsch/ansible-icinga2 pull request #39
Opened 2021-08-12 04:50 UTC by jofiedler

regex no longer matched for user and group in icinga 2.12

2021-08-25 17:27 UTC, bodsch commented
Hallo @jofiedler !
Ich habe versucht das ganze regex Thema nachzuvollziehen .. ist mir leider icht gelungen. :(
https://regex101.com/r/3LqVkq/2

2021-08-25 17:29 UTC, bodsch requested changes

2021-08-25 17:29 UTC, bodsch commented on library/icinga2_prepared_vars.py
> +        pattern = re.compile(r'.*:="(?P<var>.*[0-9A-Za-z])".*'.format(self.variable), re.MULTILINE)
Nein, das funktioniert so nicht.
Wenn "{}" entfernt wird, dann wird nicht mehr die gewünschte Variable aus dem Textblock extrahiert.

2021-10-29 06:35 UTC, bodsch commented
@jofiedler ich werde den PR am 1.11. schließen, wenn von deiner Seite kein weiteres Veto vernehmbar ist.

2021-11-01 08:15 UTC, jofiedler commented
Hallo Bodo,
alles klar.
Grüße
Jochen

Von: Bo.Sch. ***@***.***>
Gesendet: Freitag, 29. Oktober 2021 08:36
An: bodsch/ansible-icinga2 ***@***.***>
Cc: Fiedler, Jochen ***@***.***>; Mention ***@***.***>
Betreff: Re: [bodsch/ansible-icinga2] Update icinga2_prepared_vars.py (#39)


@jofiedler<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjofiedler&data=04%7C01%7C%7Cb1070819f9bd404a21a708d99aa651dd%7Cccb50e1eda1642eba480d8e2adf5bc9d%7C0%7C0%7C637710861393810245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QIWz5%2B7BoKqcfzB1n77k3KBslF30YYvqizJj%2FPmmlQ0%3D&reserved=0> ich werde den PR am 1.11. schließen, wenn von deiner Seite kein weiteres Veto vernehmbar ist.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbodsch%2Fansible-icinga2%2Fpull%2F39%23issuecomment-954467928&data=04%7C01%7C%7Cb1070819f9bd404a21a708d99aa651dd%7Cccb50e1eda1642eba480d8e2adf5bc9d%7C0%7C0%7C637710861393820201%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ywIwmmdzfX76qwFAZMNFsyGE6RqPRFvGEOPcgMX1Xqc%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMB2662OKFNLF6X2Y2YHCXTUJJFERANCNFSM5CAGDYNA&data=04%7C01%7C%7Cb1070819f9bd404a21a708d99aa651dd%7Cccb50e1eda1642eba480d8e2adf5bc9d%7C0%7C0%7C637710861393820201%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R%2F%2F8eZKJ7uxqutZ0FVpfzhInQjcqff6R%2Fnp%2BdYzMlwY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cb1070819f9bd404a21a708d99aa651dd%7Cccb50e1eda1642eba480d8e2adf5bc9d%7C0%7C0%7C637710861393830165%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sdLFkJHpj8On3MGdkLVH2BjDBojXiGXlrrecvk7RnJU%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cb1070819f9bd404a21a708d99aa651dd%7Cccb50e1eda1642eba480d8e2adf5bc9d%7C0%7C0%7C637710861393840114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qe333ld2zQb4JjKZBp4YKxr9kmnrHrx0lz8YPWKBTvs%3D&reserved=0>.


targens GmbH

Firmensitz: Calwer Straße 33, 70173 Stuttgart
Registergericht: Amtsgericht Stuttgart, HRB 747196
Geschäftsführer: Dr. Lars A. Ludwig

2021-11-02 04:24 UTC, bodsch commented
Problem nicht nachstellbar.

2021-11-02 04:24 UTC, closed without merging